name: Nextlot CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # ==========================
  # 1. FRONTEND JOB (React)
  # ==========================
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Run tests
        run: npm test --if-present

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  # ==========================
  # 2. BACKEND JOB (FastAPI)
  # ==========================
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        run: pytest

      - name: Lint
        run: flake8 .

      - name: Upload backend app
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend

  # ==========================
  # 3. DEPLOY JOB
  # ==========================
  deploy:
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: backend

      # Example: Deploy with Docker Compose
      - name: Set up Docker
        uses: docker/setup-b
